name: Changes Merged Staging to main
on:
  push:
    branches:
      - staging
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Merge feat into staging
        run: |
          git checkout main
          git merge origin/staging --no-edit
          git push origin main
