name: Merge Staging to Main
on:
  push:
    branches:
      - staging
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Authenticate with GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Konay1092/ci_cd_tutorial.git

      - name: Fetch all branches
        run: git fetch --prune --all

      - name: Merge staging into main
        run: |
          git checkout -B main origin/main
          git merge origin/staging --no-edit
          git push origin main
