name: Merge Staging to Main
on:
  push:
    branches:
      - staging
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures all branches are fetched

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --prune --unshallow

      - name: Merge staging into main
        run: |
          git checkout -B main origin/main
          git merge origin/staging --no-edit
          git push origin main
